using System.Collections.Generic;

namespace DDoor.ArchipelagoRandomizer;

public static class Items
{
    public readonly struct Item(
            string itemChangerName,
            long apItemId
        )
    {
        public readonly string itemChangerName = itemChangerName;
        public readonly long apItemId = apItemId;
    }

    public readonly static List<Item> itemData = [
        new Item("Life Seed",1),
        new Item("Fire",2),
        new Item("Bomb",3),
        new Item("Hookshot",4),
        new Item("Arrow Upgrade",5),
        new Item("Rogue Daggers",6),
        new Item("Discarded Umbrella",7),
        new Item("Reaper's Greatsword",8),
        new Item("Thunder Hammer",9),
        new Item("Vitality Shard",10),
        new Item("Magic Shard",11),
        new Item("100 Souls",12),
        new Item("Pink Key",13),
        new Item("Green Key",14),
        new Item("Yellow Key",15),
        new Item("Engagement Ring",16),
        new Item("Old Compass",17),
        new Item("Incense",18),
        new Item("Undying Blossom",19),
        new Item("Old Photograph",20),
        new Item("Sludge-Filled Urn",21),
        new Item("Token of Death",22),
        new Item("Rusty Garden Trowel",23),
        new Item("Captain's Log",24),
        new Item("Giant Arrowhead",25),
        new Item("Malformed Seed",26),
        new Item("Corrupted Antler",27),
        new Item("Magical Forest Horn",28),
        new Item("Ancient Crown",29),
        new Item("Grunt's Old Mask",30),
        new Item("Ancient Door Scale Model",31),
        new Item("Modern Door Scale Model",32),
        new Item("Rusty Belltower Key",33),
        new Item("Surveillance Device",34),
        new Item("Shiny Medallion",35),
        new Item("Ink-Covered Teddy Bear",36),
        new Item("Death's Contract",37),
        new Item("Makeshift Soul Key",38),
        new Item("Mysterious Locket",39),
        new Item("Red Ancient Tablet of Knowledge",40),
        new Item("Yellow Ancient Tablet of Knowledge",41),
        new Item("Green Ancient Tablet of Knowledge",42),
        new Item("Cyan Ancient Tablet of Knowledge",43),
        new Item("Blue Ancient Tablet of Knowledge",44),
        new Item("Purple Ancient Tablet of Knowledge",45),
        new Item("Lever-Bomb Exit",46),
        new Item("Lever-Cemetery Sewer",47),
        new Item("Lever-Guardian of the Door Access",48),
        new Item("Lever-Cemetery Shortcut to East Tree",49),
        new Item("Lever-Cemetery East Tree",50),
        new Item("Lever-Catacombs Tower",51),
        new Item("Lever-Cemetery Exit to Estate",52),
        new Item("Lever-Catacombs Exit",53),
        new Item("Lever-Hookshot Silent Servant",54),
        new Item("Lever-Sailor Turncam Upper",55),
        new Item("Lever-Sailor Turncam Lower",56),
        new Item("Lever-Sailor Greatsword Gate",57),
        new Item("Lever-Lockstone East Start Shortcut",58),
        new Item("Lever-Lockstone Entrance",59),
        new Item("Lever-Lockstone East Lower",60),
        new Item("Lever-Lockstone Upper Shortcut",61),
        new Item("Lever-Lockstone Dual Laser Puzzle",62),
        new Item("Lever-Lockstone Tracking Beam Puzzle",63),
        new Item("Lever-Lockstone Vertical Laser Puzzle",64),
        new Item("Lever-Lockstone North Puzzle",65),
        new Item("Lever-Lockstone Shrine",66),
        new Item("Lever-Lockstone Hookshot Puzzle",67),
        new Item("Lever-Lockstone Upper Puzzle",68),
        new Item("Lever-Lockstone Upper Dual Laser Puzzle",69),
        new Item("Lever-Watchtowers Before Ice Arena",70),
        new Item("Lever-Watchtowers After Ice Skating",71),
        new Item("Lever-Watchtowers After Boomers",72),
        new Item("Lever-Ruins Settlement Gate",73),
        new Item("Lever-Ruins Upper Dungeon Entrance",74),
        new Item("Lever-Ruins Ladder Left of Lord of Doors Arena",75),
        new Item("Lever-Ruins Entrance Ladder Shortcut",76),
        new Item("Lever-Ruins Main Gate",77),
        new Item("Lever-Dungeon Entrance Right Gate",78),
        new Item("Lever-Dungeon Entrance Left Gate",79),
        new Item("Lever-Dungeon Above Rightmost Crow",80),
        new Item("Lever-Fortress Bomb",81),
        new Item("Lever-Fortress Main Gate",82),
        new Item("Lever-Fortress Central Shortcut",83),
        new Item("Lever-Fortress Statue",84),
        new Item("Lever-Fortress Watchtower Lower",85),
        new Item("Lever-Fortress Bridge",86),
        new Item("Lever-Fortress Pre-Main Gate",87),
        new Item("Lever-Fortress Watchtower Upper",88),
        new Item("Lever-Fortress North West",89),
        new Item("Lever-Estate Elevator Left",90),
        new Item("Lever-Estate Elevator Right",91),
        new Item("Lever-Garden of Love",92),
        new Item("Lever-Garden of Life End",93),
        new Item("Lever-Garden of Peace",94),
        new Item("Lever-Garden of Joy",95),
        new Item("Lever-Garden of Love Turncam",96),
        new Item("Lever-Garden of Life Lanterns",97),
        new Item("Lever-Estate Underground Urn Shed",98),
        new Item("Lever-Manor Big Pot Arena",99),
        new Item("Lever-Manor Bookshelf Shortcut",100),
        new Item("Grove of Spirits Door",101),
        new Item("Lost Cemetery Door",102),
        new Item("Stranded Sailor Door",103),
        new Item("Castle Lockstone Door",104),
        new Item("Camp of the Free Crows Door",105),
        new Item("Old Watchtowers Door",106),
        new Item("Betty's Lair Door",107),
        new Item("Overgrown Ruins Door",108),
        new Item("Mushroom Dungeon Door",109),
        new Item("Flooded Fortress Door",110),
        new Item("Throne of the Frog King Door",111),
        new Item("Estate of the Urn Witch Door",112),
        new Item("Ceramic Manor Door",113),
        new Item("Inner Furnace Door",114),
        new Item("The Urn Witch's Laboratory Door",115),
        new Item("Giant Soul of The Urn Witch",116),
        new Item("Giant Soul of The Frog King",117),
        new Item("Giant Soul of Betty",118),
        new Item("Crow-Manor After Torch Puzzle",119),
        new Item("Crow-Manor Imp Loft",120),
        new Item("Crow-Manor Library",121),
        new Item("Crow-Manor Bedroom",122),
        new Item("Crow-Dungeon Hall",123),
        new Item("Crow-Dungeon Water Arena",124),
        new Item("Crow-Dungeon Cobweb",125),
        new Item("Crow-Dungeon Rightmost",126),
        new Item("Crow-Lockstone East",127),
        new Item("Crow-Lockstone West",128),
        new Item("Crow-Lockstone West Locked",129),
        new Item("Crow-Lockstone South West",130),
    ];
}