using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Newtonsoft.Json;

namespace DDoor.ArchipelagoRandomizer;

public static class Locations
{
    static Locations()
    {
        PopulateLocationsFromJson();
    }
    public readonly struct Location(
        string itemChangerName,
        long apLocationId
    )
    {
        public readonly string itemChangerName = itemChangerName;
        public readonly long apLocationId = apLocationId;
    }
    public static List<Location> locationData;

    private static void PopulateLocationsFromJson()
    {
        Assembly assembly = Assembly.GetExecutingAssembly();
		using StreamReader reader = new StreamReader(assembly.GetManifestResourceStream("DDoor.ArchipelagoRandomizer.Data.Locations.json"));
		locationData = JsonConvert.DeserializeObject<List<Location>>(reader.ReadToEnd());
	}
    // public readonly static List<Location> locationData = [
    // new Location("Fire Avarice", 1),
    // new Location("Bomb Avarice",2),
    // new Location("Hookshot Avarice",3),
    // new Location("Fire Silent Servant",4),
    // new Location("Bomb Silent Servant",5),
    // new Location("Hookshot Silent Servant",6),
    // new Location("Arrow Silent Servant",7),
    // new Location("Rogue Daggers",8),
    // new Location("Discarded Umbrella",9),
    // new Location("Reaper's Greatsword",10),
    // new Location("Thunder Hammer",11),
    // new Location("Betty",12),
    // new Location("Frog King",13),
    // new Location("Grandma",14),
    // new Location("Heart Shrine-Cemetery Behind Entrance",15),
    // new Location("Magic Shrine-Cemetery After Smough Arena",16),
    // new Location("Heart Shrine-Cemetery Winding Bridge End",17),
    // new Location("Heart Shrine-Hookshot Arena",18),
    // new Location("Magic Shrine-Sailor Turncam",19),
    // new Location("Magic Shrine-Lockstone Secret West",20),
    // new Location("Heart Shrine-Camp Ice Skating",21),
    // new Location("Magic Shrine-Ruins Hookshot Arena",22),
    // new Location("Magic Shrine-Ruins Turncam",23),
    // new Location("Heart Shrine-Dungeon Water Arena",24),
    // new Location("Heart Shrine-Ruins Sewer",25),
    // new Location("Magic Shrine-Fortress Bow Secret",26),
    // new Location("Magic Shrine-Estate Left of Manor",27),
    // new Location("Heart Shrine-Garden of Life",28),
    // new Location("Magic Shrine-Manor Bathroom Puzzle",29),
    // new Location("Heart Shrine-Furnace Cart Puzzle",30),
    // new Location("Engagement Ring",31),
    // new Location("Old Compass",32),
    // new Location("Incense",33),
    // new Location("Undying Blossom",34),
    // new Location("Old Photograph",35),
    // new Location("Sludge-Filled Urn",36),
    // new Location("Token of Death",37),
    // new Location("Rusty Garden Trowel",38),
    // new Location("Captain's Log",39),
    // new Location("Giant Arrowhead",40),
    // new Location("Malformed Seed",41),
    // new Location("Corrupted Antler",42),
    // new Location("Magical Forest Horn",43),
    // new Location("Ancient Crown",44),
    // new Location("Grunt's Old Mask",45),
    // new Location("Ancient Door Scale Model",46),
    // new Location("Modern Door Scale Model",47),
    // new Location("Rusty Belltower Key",48),
    // new Location("Surveillance Device",49),
    // new Location("Shiny Medallion",50),
    // new Location("Ink-Covered Teddy Bear",51),
    // new Location("Death's Contract",52),
    // new Location("Makeshift Soul Key",53),
    // new Location("Mysterious Locket",54),
    // new Location("Seed-Cemetery Broken Bridge",55),
    // new Location("Seed-Catacombs Tower",56),
    // new Location("Seed-Cemetery Left of Main Entrance",57),
    // new Location("Seed-Cemetery Near Tablet Gate",58),
    // new Location("Seed-Between Cemetery and Sailor",59),
    // new Location("Seed-Sailor Upper",60),
    // new Location("Seed-Lockstone Upper East",61),
    // new Location("Seed-Lockstone Soul Door",62),
    // new Location("Seed-Lockstone Behind Bars",63),
    // new Location("Seed-Lockstone Entrance West",64),
    // new Location("Seed-Lockstone North",65),
    // new Location("Seed-Camp Ledge With Huts",66),
    // new Location("Seed-Camp Stall",67),
    // new Location("Seed-Camp Rooftops",68),
    // new Location("Seed-Watchtowers Ice Skating",69),
    // new Location("Seed-Watchtowers Tablet Door",70),
    // new Location("Seed-Watchtowers Archer Platform",71),
    // new Location("Seed-Watchtowers Boxes",72),
    // new Location("Seed-Dungeon Fire Puzzle Near Water Arena",73),
    // new Location("Seed-Ruins Lord of Doors Arena",74),
    // new Location("Seed-Ruins Fire Plant Corridor",75),
    // new Location("Seed-Dungeon Water Arena Left Exit",76),
    // new Location("Seed-Ruins Right Middle",77),
    // new Location("Seed-Ruins On Settlement Wall",78),
    // new Location("Seed-Ruins Behind Boxes",79),
    // new Location("Seed-Ruins Down Through Bomb Wall",80),
    // new Location("Seed-Dungeon Above Rightmost Crow",81),
    // new Location("Seed-Dungeon Right Above Key",82),
    // new Location("Seed-Dungeon Avarice Bridge",83),
    // new Location("Seed-Fortress Watchtower",84),
    // new Location("Seed-Fortress Statue",85),
    // new Location("Seed-Fortress Bridge",86),
    // new Location("Seed-Fortress Intro Crate",87),
    // new Location("Seed-Fortress East After Statue",88),
    // new Location("Seed-Estate Family Tomb",89),
    // new Location("Seed-Estate Entrance",90),
    // new Location("Seed-Estate Hedge Gaps",91),
    // new Location("Seed-Garden of Joy",92),
    // new Location("Seed-Manor Boxes",93),
    // new Location("Seed-Manor Near Brazier",94),
    // new Location("Seed-Manor Below Big Pot Arena",95),
    // new Location("Seed-Manor Rafters",96),
    // new Location("Seed-Manor Main Room Upper",97),
    // new Location("Seed-Manor Spinny Pot Room",98),
    // new Location("Seed-Manor Library Shelf",99),
    // new Location("Seed-Cart Puzzle",100),
    // new Location("Seed-Furnace Entrance",101),
    // new Location("Seed-Inner Furnace Horizontal Pistons",102),
    // new Location("Seed-Inner Furnace Conveyor Bridge",103),
    // new Location("Seed-Inner Furnace Conveyor Gauntlet",104),
    // new Location("Soul Orb-Fire Return Upper",105),
    // new Location("Soul Orb-Hookshot Secret",106),
    // new Location("Soul Orb-Bomb Return",107),
    // new Location("Soul Orb-Bomb Secret",108),
    // new Location("Soul Orb-Hookshot Return",109),
    // new Location("Soul Orb-Fire Return Lower",110),
    // new Location("Soul Orb-Fire Secret",111),
    // new Location("Soul Orb-Catacombs Exit",112),
    // new Location("Soul Orb-Cemetery Hookshot Towers",113),
    // new Location("Soul Orb-Cemetery Under Bridge",114),
    // new Location("Soul Orb-Cemetery East Tree",115),
    // new Location("Soul Orb-Cemetery Winding Bridge End",116),
    // new Location("Soul Orb-Catacombs Room 2",117),
    // new Location("Soul Orb-Catacombs Room 1",118),
    // new Location("Soul Orb-Cemetery Gated Sewer",119),
    // new Location("Soul Orb-Catacombs Entrance",120),
    // new Location("Soul Orb-Cemetery Cave",121),
    // new Location("Soul Orb-Sailor Turncam",122),
    // new Location("Soul Orb-North Lockstone Sewer",123),
    // new Location("Soul Orb-Lockstone Hookshot North",124),
    // new Location("Soul Orb-Lockstone Exit",125),
    // new Location("Soul Orb-West Lockstone Sewer",126),
    // new Location("Soul Orb-Camp Rooftops",127),
    // new Location("Soul Orb-Camp Broken Bridge",128),
    // new Location("Soul Orb-Watchtowers Behind Barb Elevator",129),
    // new Location("Soul Orb-Dungeon Vine",130),
    // new Location("Soul Orb-Ruins Stump",131),
    // new Location("Soul Orb-Ruins Outside Left Dungeon Exit",132),
    // new Location("Soul Orb-Dungeon Cobweb",133),
    // new Location("Soul Orb-Ruins Left After Key Door",134),
    // new Location("Soul Orb-Ruins Lower Bomb Wall",135),
    // new Location("Soul Orb-Ruins Lord of Doors Arena Hookshot",136),
    // new Location("Soul Orb-Dungeon Lower Entrance",137),
    // new Location("Soul Orb-Ruins Upper Above Horn",138),
    // new Location("Soul Orb-Ruins Above Three Plants",139),
    // new Location("Soul Orb-Ruins Up Turncam Ladder",140),
    // new Location("Soul Orb-Ruins Above Entrance Gate",141),
    // new Location("Soul Orb-Ruins Upper Bomb Wall",142),
    // new Location("Soul Orb-Dungeon Left Exit Shelf",143),
    // new Location("Soul Orb-Ruins Lower Hookshot",144),
    // new Location("Soul Orb-Fortress Bomb",145),
    // new Location("Soul Orb-Fortress Hidden Sewer",146),
    // new Location("Soul Orb-Fortress Drop",147),
    // new Location("Soul Orb-Estate Access Crypt",148),
    // new Location("Soul Orb-Estate Balcony",149),
    // new Location("Soul Orb-Garden of Love Turncam",150),
    // new Location("Soul Orb-Garden of Life Hookshot Loop",151),
    // new Location("Soul Orb-Garden of Love Bomb Walls",152),
    // new Location("Soul Orb-Garden of Life Bomb Wall",153),
    // new Location("Soul Orb-Estate Broken Boardwalk",154),
    // new Location("Soul Orb-Estate Secret Cave",155),
    // new Location("Soul Orb-Estate Twin Benches",156),
    // new Location("Soul Orb-Estate Sewer Middle",157),
    // new Location("Soul Orb-Estate Sewer End",158),
    // new Location("Soul Orb-Garden of Peace",159),
    // new Location("Soul Orb-Manor Imp Loft",160),
    // new Location("Soul Orb-Manor Library Shelf",161),
    // new Location("Soul Orb-Manor Chandelier",162),
    // new Location("Soul Orb-Furnace Lantern Chain",163),
    // new Location("Soul Orb-Small Room",164),
    // new Location("Soul Orb-Furnace Entrance Sewer",165),
    // new Location("Red Ancient Tablet of Knowledge",166),
    // new Location("Yellow Ancient Tablet of Knowledge",167),
    // new Location("Green Ancient Tablet of Knowledge",168),
    // new Location("Cyan Ancient Tablet of Knowledge",169),
    // new Location("Blue Ancient Tablet of Knowledge",170),
    // new Location("Purple Ancient Tablet of Knowledge",171),
    // new Location("Estate Owl",172),
    // new Location("Ruins Owl",173),
    // new Location("Watchtowers Owl",174),
    // new Location("Lever-Bomb Exit",175),
    // new Location("Lever-Cemetery Sewer",176),
    // new Location("Lever-Guardian of the Door Access",177),
    // new Location("Lever-Cemetery Shortcut to East Tree",178),
    // new Location("Lever-Cemetery East Tree",179),
    // new Location("Lever-Catacombs Tower",180),
    // new Location("Lever-Cemetery Exit to Estate",181),
    // new Location("Lever-Catacombs Exit",182),
    // new Location("Lever-Hookshot Silent Servant",183),
    // new Location("Lever-Sailor Turncam Upper",184),
    // new Location("Lever-Sailor Turncam Lower",185),
    // new Location("Lever-Sailor Greatsword Gate",186),
    // new Location("Lever-Lockstone East Start Shortcut",187),
    // new Location("Lever-Lockstone Entrance",188),
    // new Location("Lever-Lockstone East Lower",189),
    // new Location("Lever-Lockstone Upper Shortcut",190),
    // new Location("Lever-Lockstone Dual Laser Puzzle",191),
    // new Location("Lever-Lockstone Tracking Beam Puzzle",192),
    // new Location("Lever-Lockstone Vertical Laser Puzzle",193),
    // new Location("Lever-Lockstone North Puzzle",194),
    // new Location("Lever-Lockstone Shrine",195),
    // new Location("Lever-Lockstone Hookshot Puzzle",196),
    // new Location("Lever-Lockstone Upper Puzzle",197),
    // new Location("Lever-Lockstone Upper Dual Laser Puzzle",198),
    // new Location("Lever-Watchtowers Before Ice Arena",199),
    // new Location("Lever-Watchtowers After Ice Skating",200),
    // new Location("Lever-Watchtowers After Boomers",201),
    // new Location("Lever-Ruins Settlement Gate",202),
    // new Location("Lever-Ruins Upper Dungeon Entrance",203),
    // new Location("Lever-Ruins Ladder Left of Lord of Doors Arena",204),
    // new Location("Lever-Ruins Entrance Ladder Shortcut",205),
    // new Location("Lever-Ruins Main Gate",206),
    // new Location("Lever-Dungeon Entrance Right Gate",207),
    // new Location("Lever-Dungeon Entrance Left Gate",208),
    // new Location("Lever-Dungeon Above Rightmost Crow",209),
    // new Location("Lever-Fortress Bomb",210),
    // new Location("Lever-Fortress Main Gate",211),
    // new Location("Lever-Fortress Central Shortcut",212),
    // new Location("Lever-Fortress Statue",213),
    // new Location("Lever-Fortress Watchtower Lower",214),
    // new Location("Lever-Fortress Bridge",215),
    // new Location("Lever-Fortress Pre-Main Gate",216),
    // new Location("Lever-Fortress Watchtower Upper",217),
    // new Location("Lever-Fortress North West",218),
    // new Location("Lever-Estate Elevator Left",219),
    // new Location("Lever-Estate Elevator Right",220),
    // new Location("Lever-Garden of Love",221),
    // new Location("Lever-Garden of Life End",222),
    // new Location("Lever-Garden of Peace",223),
    // new Location("Lever-Garden of Joy",224),
    // new Location("Lever-Garden of Love Turncam",225),
    // new Location("Lever-Garden of Life Lanterns",226),
    // new Location("Lever-Estate Underground Urn Shed",227),
    // new Location("Lever-Manor Big Pot Arena",228),
    // new Location("Lever-Manor Bookshelf Shortcut",229),
    // new Location("Grove of Spirits Door",230),
    // new Location("Lost Cemetery Door",231),
    // new Location("Stranded Sailor Door",232),
    // new Location("Castle Lockstone Door",233),
    // new Location("Camp of the Free Crows Door",234),
    // new Location("Old Watchtowers Door",235),
    // new Location("Betty's Lair Door",236),
    // new Location("Overgrown Ruins Door",237),
    // new Location("Mushroom Dungeon Door",238),
    // new Location("Flooded Fortress Door",239),
    // new Location("Throne of the Frog King Door",240),
    // new Location("Estate of the Urn Witch Door",241),
    // new Location("Ceramic Manor Door",242),
    // new Location("Inner Furnace Door",243),
    // new Location("The Urn Witch's Laboratory Door",244),
    // new Location("Key-Cemetery Central",245),
    // new Location("Key-Cemetery Grey Crow",246),
    // new Location("Key-Camp of the Free Crows",247),
    // new Location("Key-Lockstone West",248),
    // new Location("Key-Lockstone North",249),
    // new Location("Key-Overgrown Ruins",250),
    // new Location("Key-Dungeon Hall",251),
    // new Location("Key-Dungeon Right",252),
    // new Location("Key-Dungeon Near Water Arena",253),
    // new Location("Key-Manor Under Dining Room",254),
    // new Location("Key-Manor After Spinny Pot Room",255),
    // new Location("Key-Manor Library",256),
    // new Location("Crow-Manor After Torch Puzzle",257),
    // new Location("Crow-Manor Imp Loft",258),
    // new Location("Crow-Manor Library",259),
    // new Location("Crow-Manor Bedroom",260),
    // new Location("Crow-Dungeon Hall",261),
    // new Location("Crow-Dungeon Water Arena",262),
    // new Location("Crow-Dungeon Cobweb",263),
    // new Location("Crow-Dungeon Rightmost",264),
    // new Location("Crow-Lockstone East",265),
    // new Location("Crow-Lockstone West",266),
    // new Location("Crow-Lockstone West Locked",267),
    // new Location("Crow-Lockstone South West",268),
    // ];
}
